spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/graduation_thesis_ver2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:9000/realms/hung2004/protocol/openid-connect/certs}

server.error.include-message=always

keycloak.adminClientId=${KEYCLOAK_ADMIN_CLIENT_ID:graduation_thesis_ver2}
keycloak.adminClientSecret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}
keycloak.realm=${KEYCLOAK_REALM:hung2004}
keycloak.urls.auth=${KEYCLOAK_URLS_AUTH:http://localhost:9000}
keycloak.admin-user=${KEYCLOAK_ADMIN_USER:}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:}

keycloak.authorization.resources = public-resource
springdoc.swagger-ui.path=/api/public/swagger-ui.html

logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.upload.dir=${APP_UPLOAD_DIR:./data/student_faces}
app.document.dir=${APP_DOCUMENT_DIR:./data/document}
app.ai.proctor.url=${APP_AI_PROCTOR_URL:http://localhost:8899}
app.timezone=${APP_TIMEZONE:Asia/Ho_Chi_Minh}

app.bootstrap.admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap.admin.username=${APP_BOOTSTRAP_ADMIN_USERNAME:admin}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:admin_system@example.com}
app.bootstrap.admin.first-name=${APP_BOOTSTRAP_ADMIN_FIRST_NAME:System}
app.bootstrap.admin.last-name=${APP_BOOTSTRAP_ADMIN_LAST_NAME:Admin}
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:}

