package com.example.backend.controller;

import com.example.backend.dto.*;
import com.example.backend.service.DocumentService;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

@RestController
@RequestMapping("/api/documents")
public class DocumentController {

    private final DocumentService documentService;

    public DocumentController(DocumentService documentService) {
        this.documentService = documentService;
    }

    @PostMapping(value = "/upload", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<DocumentResponseDto> uploadFile(
            @RequestParam("courseId") Long courseId,
            @RequestParam(value = "parentFolderId", required = false) Long parentFolderId,
            @RequestParam("file") MultipartFile file,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        String name = jwt.getClaimAsString("name");
        return ResponseEntity.ok(documentService.uploadFile(courseId, parentFolderId, file, sub, name));
    }

    @GetMapping("/download/{docId}")
    public ResponseEntity<Resource> downloadFile(
            @PathVariable Long docId,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        Resource resource = documentService.downloadFile(docId, sub, null);
        
        // Strip out the prefix generated by UUID for cleaner filename download
        String originalFilename = resource.getFilename();
        if (originalFilename != null && originalFilename.contains("_")) {
            // Find first underscore index and extract after it to restore the original name
            int firstUnderscore = originalFilename.indexOf("_");
            if (firstUnderscore > 0 && firstUnderscore < originalFilename.length() - 1) {
                originalFilename = originalFilename.substring(firstUnderscore + 1);
            }
        }

        return ResponseEntity.ok()
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + originalFilename + "\"")
                .body(resource);
    }

    @PostMapping("/folder")
    public ResponseEntity<DocumentResponseDto> createFolder(
            @RequestBody CreateFolderRequest request,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        String name = jwt.getClaimAsString("name");
        return ResponseEntity.ok(documentService.createFolder(
                request.getCourseId(),
                request.getParentFolderId(),
                request.getFolderName(),
                sub,
                name
        ));
    }

    @GetMapping("/class/{classId}")
    public ResponseEntity<List<DocumentResponseDto>> getDocuments(
            @PathVariable Long classId,
            @RequestParam(value = "parentFolderId", required = false) Long parentFolderId,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        return ResponseEntity.ok(documentService.getDocuments(classId, parentFolderId, sub, null));
    }

    @DeleteMapping("/{docId}")
    public ResponseEntity<Void> deleteDocument(
            @PathVariable Long docId,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        documentService.deleteDocument(docId, sub, null);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/class/{classId}/permissions")
    public ResponseEntity<List<StudentPermissionResponseDto>> getStudentPermissions(
            @PathVariable Long classId,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        return ResponseEntity.ok(documentService.getStudentPermissions(classId, sub, null));
    }

    @PostMapping("/class/{classId}/permissions/student/{studentId}")
    public ResponseEntity<Void> updateStudentPermissions(
            @PathVariable Long classId,
            @PathVariable Long studentId,
            @RequestBody UpdatePermissionRequest request,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        documentService.updateStudentPermissions(
                classId,
                studentId,
                request.getCanUpload(),
                request.getCanDownload(),
                sub
        );
        return ResponseEntity.ok().build();
    }

    @PostMapping("/class/{classId}/permissions/bulk")
    public ResponseEntity<Void> updateClassPermissionsBulk(
            @PathVariable Long classId,
            @RequestBody UpdatePermissionRequest request,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        documentService.updateClassPermissionsBulk(
                classId,
                request.getCanUpload(),
                request.getCanDownload(),
                sub
        );
        return ResponseEntity.ok().build();
    }

    @GetMapping("/class/{classId}/my-permissions")
    public ResponseEntity<StudentPermissionResponseDto> getMyPermission(
            @PathVariable Long classId,
            @AuthenticationPrincipal Jwt jwt) {
        String sub = jwt.getClaimAsString("sub");
        return ResponseEntity.ok(documentService.getMyPermission(classId, sub));
    }
}
